services:
  backend:
    build: ./backend
    ports:
      - "3001:3001"
    env_file:
      - ./.env
    environment:
      DATABASE_URL: postgres://user:password@db:5432/openvlog
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      - db
  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: openvlog
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/db/init.sql:/docker-entrypoint-initdb.d/init.sql
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
volumes:
  postgres_data: