version: '3.9'
services:
  traefik:
    image: traefik:v3.0
    command:
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --certificatesresolvers.lets.acme.email=${ACME_EMAIL}
      - --certificatesresolvers.lets.acme.storage=/letsencrypt/acme.json
      - --certificatesresolvers.lets.acme.httpchallenge=true
      - --certificatesresolvers.lets.acme.httpchallenge.entrypoint=web
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik_letsencrypt:/letsencrypt
    networks:
      - public

  backend:
    labels:
      - traefik.enable=true
      - traefik.http.routers.api.rule=Host(`${API_HOST}`)
      - traefik.http.routers.api.entrypoints=websecure
      - traefik.http.routers.api.tls.certresolver=lets
      - traefik.http.services.api.loadbalancer.server.port=3001
      - traefik.http.routers.api-http.rule=Host(`${API_HOST}`)
      - traefik.http.routers.api-http.entrypoints=web
  - traefik.http.routers.api-http.middlewares=redirect-to-https
  - traefik.http.middlewares.api-ratelimit.ratelimit.average=20
  - traefik.http.middlewares.api-ratelimit.ratelimit.burst=40
  - traefik.http.routers.api.middlewares=api-ratelimit

  frontend:
    labels:
      - traefik.enable=true
      - traefik.http.routers.front.rule=Host(`${APP_HOST}`)
      - traefik.http.routers.front.entrypoints=websecure
      - traefik.http.routers.front.tls.certresolver=lets
      - traefik.http.services.front.loadbalancer.server.port=80
      - traefik.http.routers.front-http.rule=Host(`${APP_HOST}`)
      - traefik.http.routers.front-http.entrypoints=web
      - traefik.http.routers.front-http.middlewares=redirect-to-https

  # Redirect middleware definition (dynamic via labels)
  traefik-middleware:
    image: traefik/whoami # lightweight placeholder to attach middleware labels
    labels:
      - traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https
    deploy:
      replicas: 0

networks:
  public:
    external: false

volumes:
  traefik_letsencrypt:
